CREATE TABLE IF NOT EXISTS portfolio_holdings (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL UNIQUE,
  name_zh VARCHAR(50),
  name_en VARCHAR(100),
  category VARCHAR(10),
  shares INTEGER,
  cost_basis NUMERIC(12,2),
  market_value NUMERIC(12,2),
  pnl NUMERIC(12,2),
  pnl_pct NUMERIC(8,4),
  owned BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO portfolio_holdings (symbol, name_zh, name_en, category, owned)
VALUES
  ('00403A.TW', '主動統一升級50', 'UPAMC Taiwan 50 Upgrade Active ETF', 'ETF', true),
  ('0050.TW', '元大台灣50', 'Yuanta Taiwan 50 ETF', 'ETF', true),
  ('0052.TW', '富邦科技', 'Fubon Technology ETF', 'ETF', true),
  ('0056.TW', '元大高股息', 'Yuanta Taiwan Dividend Plus ETF', 'ETF', true),
  ('006208.TW', '富邦台50', 'Fubon Taiwan 50 ETF', 'ETF', true),
  ('00878.TW', '國泰永續高股息', 'Cathay Taiwan ESG Sustainability High Dividend ETF', 'ETF', true),
  ('00881.TW', '國泰台灣科技龍頭', 'Cathay Taiwan Technology Leaders ETF', 'ETF', true),
  ('00919.TW', '群益台灣精選高息', 'Capital Taiwan Select High Dividend ETF', 'ETF', true),
  ('00929.TW', '復華台灣科技優息', 'Fuh Hwa Taiwan Technology Dividend ETF', 'ETF', true),
  ('009816.TW', '凱基台灣TOP50', 'KGI Taiwan TOP50 ETF', 'ETF', true),
  ('00981A.TW', '主動統一台股增長', 'UPAMC Taiwan Growth Active ETF', 'ETF', true),
  ('00991A.TW', '主動復華未來50', 'Fuh Hwa Future 50 Active ETF', 'ETF', true),
  ('2002.TW', '中鋼', 'China Steel', '股票', true),
  ('2103.TW', '台橡', 'TSRC', '股票', true),
  ('2301.TW', '光寶科', 'Lite-On Technology', '股票', true),
  ('2308.TW', '台達電', 'Delta Electronics', '股票', true),
  ('2317.TW', '鴻海', 'Hon Hai Precision', '股票', true),
  ('2327.TW', '國巨', 'Yageo', '股票', true),
  ('2330.TW', '台積電', 'Taiwan Semiconductor Manufacturing', '股票', true),
  ('2337.TW', '旺宏', 'Macronix', '股票', true),
  ('2454.TW', '聯發科', 'MediaTek', '股票', true),
  ('2481.TW', '強茂', 'Pan Jit International', '股票', true),
  ('2492.TW', '華新科', 'Walsin Technology', '股票', true),
  ('2618.TW', '長榮航', 'EVA Airways', '股票', true),
  ('3026.TW', '禾伸堂', 'Holy Stone Enterprise', '股票', true),
  ('3257.TW', '虹冠電', 'Champion Microelectronic', '股票', true),
  ('3357.TW', '臺慶科', 'Taiwan Chinsan Electronic', '股票', true),
  ('3481.TW', '群創', 'Innolux', '股票', true),
  ('3491.TW', '昇達科', 'Universal Microwave Technology', '股票', true),
  ('5289.TW', '宜鼎', 'Innodisk', '股票', true),
  ('6442.TW', '光聖', 'EZconn', '股票', true),
  ('6770.TW', '力積電', 'Powerchip Semiconductor Manufacturing', '股票', true),
  ('6805.TW', '富世達', 'Fositek', '股票', true),
  ('6919.TW', '康霈', 'Caliway Biopharmaceuticals', '股票', true),
  ('8261.TW', '富鼎', 'A-Power Electronics', '股票', true),
  ('8299.TW', '群聯', 'Phison Electronics', '股票', true)
ON CONFLICT (symbol) DO UPDATE
SET name_zh = EXCLUDED.name_zh,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    owned = EXCLUDED.owned,
    updated_at = NOW();
